workspace_root: &workspace_root
  /go/src/github.com/hashicorp/terraform-google-consul

defaults: &defaults
  working_directory: *workspace_root
  docker:
  - image: 087285199408.dkr.ecr.us-east-1.amazonaws.com/circle-ci-test-image-base:go1.11
  environment:
    # This module has not been updated for tf12 syntax
    TERRAFORM_VERSION: 0.11.14

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: *workspace_root
      - restore_cache:
          keys:
            - dep-{{ checksum "test/Gopkg.lock" }}
      - run: configure-environment-for-gruntwork-module --go-src-path test --use-go-dep --circle-ci-2 --terraform-version ${TERRAFORM_VERSION}
      - save_cache:
          key: dep-{{ checksum "test/Gopkg.lock" }}
          paths:
          - /go/src/github.com/hashicorp/terraform-google-consul/test/vendor
      - persist_to_workspace:
          root: *workspace_root
          paths: test/vendor
  test:
    <<: *defaults
    steps:
      - checkout
      - run: echo 'export PATH=$HOME/terraform:$HOME/packer:$PATH' >> $BASH_ENV
      - attach_workspace:
          at: *workspace_root
      # Write service account creds to disk where the API expects them
      - run: |
          export GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcloud.json" && \
          echo $GCLOUD_SERVICE_KEY > /tmp/gcloud.json && \
          run-go-tests --circle-ci-2 --path test

workflows:
  version: 2
  build-and-test:
    jobs:
    - build
    - test:
        requires:
        - build
